
int countJOBDSL = 0
int countNonJobDSL = 0
int countJOBDSLInLab = 0
int countNonJobDSLInLab = 0

jobs = Jenkins.instance.getAllItems()
jobs.each { j ->
  if (j instanceof com.cloudbees.hudson.plugins.folder.Folder) { return }
  
  String strDescr = ""
  String strName  = ""
  strDescr = j.getDescription()
  strName = j.fullName
  
  boolean isJOBDSL = false;
  boolean isInLab = false
  
  if(strDescr != null)
  {
    isJOBDSL = strDescr.indexOf("generated by JobDSL") !=-1? true: false;
  }
  if(strName != null)
  {
    isInLab = strName.indexOf("lab/") !=-1? true: false; 
  }
  if(!isJOBDSL && !isInLab)
  {
    //println 'DESCRIPTION: ' + j.getDescription()
    println "[JOB not created by JOBDSL: ]"
    println "[Job FullName:              ]  ${j.fullName}"
    println "[Job type:                  ]  ${j.getClass()}"
    println("")
    countNonJobDSL += 1
  }
  if(isJOBDSL && isInLab)
  {
    countJOBDSLInLab += 1
  }
  if(!isJOBDSL && isInLab)
  {
    countNonJobDSLInLab += 1
  }
  if(isJOBDSL && !isInLab)
  {
    countJOBDSL += 1
  } 
}
println "[JOBS count NOT created by JOBDSL:           ]  ${countNonJobDSL}"
println "[JOBS count     created by JOBDSL:           ]  ${countJOBDSL}"
println("")
println "[JOBS count NOT created by JOBDSL: In /lab:  ]  ${countNonJobDSLInLab}"
println "[JOBS count     created by JOBDSL: In /lab:  ]  ${countJOBDSLInLab}"
//
''
